spring:
  datasource:
    url: jdbc:mysql://3.38.179.92:3306/moa
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ssafy
  jpa:
    generate-ddl: true
    show-sql: true