spring:
  datasource:
    url: jdbc:mysql://3.38.179.92:3306/moa
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ssafy
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  redis:
    port: 6379
    host: 3.38.179.92
    password: ssafy
  mail:
    host: smtp.naver.com
    port: 465
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
            trust: smtp.naver.com
  profiles:
    include:
      - mail

jwt:
  secret-key: WGmDjeValRGtlGnSOLmXPW8Ht36zv571HcMi1HnG9TTsAzG5q5SW8cGkLJKf7L2CTWqI7K27tmdFgakdhBtoFQ==
  token-validity-in-sec: 3600 #1시간
  refresh-token-validity-in-sec: 604800 #1주

server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ssafy
    key-store-type: PKCS12