spring:
  datasource:
    url: jdbc:mysql://3.38.179.92:3306/moa
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    generate-ddl: true
    show-sql: true